# Generated by Django 4.0 on 2022-01-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simPage', '0002_alter_tennisplayer_utr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisplayer',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
