# Generated by Django 4.0 on 2022-01-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simPage', '0004_tennisplayer_drawnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnerPlayer', models.TextField()),
                ('loserPlayer', models.TextField()),
                ('round', models.IntegerField()),
            ],
        ),
    ]
